version: "3"

services:
  blog:
    build: .
    container_name: blog_website
    entrypoint: /app/blog/docker-entrypoint.sh
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1-alpine3.19
    container_name: blog_database
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
