version: "3"

services:
  php:
    build: .
    container_name: grilli_website
    volumes:
      - website:/app/grilli
    env_file: .env
    entrypoint: /app/grilli/docker-entrypoint.sh

  nginx:
    image: nginx:1.25.3-alpine3.18-slim
    container_name: grilli_nginx
    ports:
      - 80:80
    volumes:
      - .docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf
      - website:/app/grilli

volumes:
  website:
