version: "3"

services:
  client:
    build:
      context: .
      args:
        - BUILD_DIR_PATH=./client
    env_file: ./client/.env
    container_name: "make_me_watch_client"
    command: node build
    

  caddy:
    image: caddy:2.7.6-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./client/Caddyfile:/etc/caddy/Caddyfile

  server:
    build:
      context: .
      args:
        - BUILD_DIR_PATH=./server
    container_name: "make_me_watch_server"
    command: node dist/main.js
