version: "3"

services:
  client:
    build: ./client
    container_name: "make_me_watch_client"

  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./client/Caddyfile:/etc/caddy/Caddyfile

  server:
    build: ./server
    container_name: "make_me_watch_server"
